// The bot's voice. Every user-facing sentence lives here, in English and Arabic.
// Each function returns Telegram HTML.

import { HR, esc } from "./text.js";

const EN = {
  welcome: (name) =>
    `✨ <b>Hi${name ? " " + esc(name) : ""}, I'm Black Fighters.</b>\n${HR}\nSend me a <b>lecture</b> (PDF, slides, Word, text) or a <b>photo of your notes</b>. I'll read it, then summarize it, quiz you, build flashcards, or answer your questions from it.\n\n<i>Or just ask me anything.</i>`,
  menu: `🏠 <b>Main menu</b>\n${HR}\nSend a file or a photo, or ask me anything.`,
  fileReady: ({ title, words }) =>
    `📄 <b>${esc(title)}</b>\n${HR}\n${words ? `Read <b>${words.toLocaleString("en-US")}</b> words. ` : ""}What should I do with it?`,
  textReady: ({ words }) => `📝 <b>Text received</b>\n${HR}\n${words} words. What should I do with it?`,
  reading: "📖 Reading your file…",
  extracting: "🔍 Extracting text…",
  thinking: "🧠 Thinking…",
  writing: "✍️ Writing…",
  askPrompt: `💬 <b>Ask away</b>\n${HR}\nType your question. I'll answer from the file you sent, or from general knowledge if you haven't sent one.`,
  topicPrompt: `🎯 <b>Quiz on a topic</b>\n${HR}\nType a topic, for example <i>supply and demand</i>.`,
  noInput: `📎 <b>Nothing to work on yet</b>\n${HR}\nSend a file, a photo, or paste some text first.`,
  tooBig: (mb) => `⚠️ That file is over <b>${mb} MB</b>. Telegram bots can download up to ${mb} MB. Try a smaller file.`,
  unsupported: "⚠️ That file type isn't supported yet. Send a PDF, Word (.docx), PowerPoint (.pptx), text, or an image.",
  unreadable: "⚠️ I couldn't read any text there. Try a PDF with selectable text, or a clearer photo.",
  failed: "⚠️ The AI is busy right now. Please try again in a moment.",
  quotaReached: (limit, resetIn) =>
    `⛔ <b>Daily limit reached</b>\n${HR}\nYou've used all <b>${limit}</b> tasks for today. Come back in <b>${resetIn}</b>. Questions and chat stay free.`,
  busy: "⏳ Still working on your last request. Hang on a moment.",
  quizIntro: (n) => `🧠 <b>Quiz time</b>\n${HR}\n<b>${n}</b> questions. Tap an answer. Good luck.`,
  quizQuestion: ({ index, total, q }) => `🧠 <b>Question ${index} of ${total}</b>\n${HR}\n${esc(q)}`,
  right: (explanation) => `✅ <b>Correct.</b>${explanation ? `\n<i>${esc(explanation)}</i>` : ""}`,
  wrong: (correct, explanation) =>
    `❌ <b>Not quite.</b>\nThe answer is <b>${esc(correct)}</b>.${explanation ? `\n<i>${esc(explanation)}</i>` : ""}`,
  quizDone: (score, total) => {
    const pct = total ? Math.round((score / total) * 100) : 0;
    const verdict = pct === 100 ? "Flawless." : pct >= 70 ? "Strong work." : pct >= 40 ? "Good start. Review the misses." : "Keep at it. Try again after a quick review.";
    return `🏆 <b>Score: ${score} / ${total}</b> (${pct}%)\n${HR}\n${verdict}`;
  },
  styles: `🎨 <b>Choose a style</b>\n${HR}\nEach style is a different way to study the same material. The result is a clean HTML document you can open anywhere and print to PDF.`,
  styleLanguage: "Output language",
  figureAdded: (caption, n) => `🖼️ <b>Figure added</b>${caption ? `: ${esc(caption)}` : ""}\n<i>${n} figure${n === 1 ? "" : "s"} ready for the next document.</i>`,
  figureFull: "⚠️ You already have 6 figures for this material. Start a new file to add more.",
  figureTooBig: "⚠️ That image is over 900 KB. Send a smaller photo.",
  docReady: "📎 The document is attached. Open it in any browser, or print it to PDF.",
  docCaption: (name) => `📎 ${name}\nOpen in any browser. Print, then Save as PDF.`,
  plansTitle: `⭐ <b>Plans</b>\n${HR}\nPay with Telegram Stars. No card, no account, no outside payment provider.`,
  paid: (name, until) => `🎉 <b>${esc(name)} is active</b>\n${HR}\nValid until <b>${esc(until)}</b>. Enjoy the extra room.`,
  paidFailed: "⚠️ That payment could not be matched to a plan. If you were charged, contact the team with your receipt.",
  deckAdded: (n) => `🗂️ ${n} card${n === 1 ? "" : "s"} added to your review deck. Use /review to practise them.`,
  reviewNone: (total) => total ? `✅ <b>Nothing due right now.</b>\n${HR}\n${total} cards in your deck. Come back later.` : `🗂️ <b>Your review deck is empty.</b>\n${HR}\nGenerate flashcards from any material and they will be saved here.`,
  reviewQuestion: (q, left) => `🔁 <b>Review</b> · ${left} due\n${HR}\n${esc(q)}`,
  reviewAnswer: (q, a) => `🔁 <b>Review</b>\n${HR}\n<b>${esc(q)}</b>\n\n${esc(a)}\n\n<i>How well did you know it?</i>`,
  reviewNext: (days) => days < 1 ? `✅ Got it. You'll see it again in about 10 minutes.` : `✅ Got it. Next review in ${days} day${days === 1 ? "" : "s"}.`,
  grades: ["Again", "Hard", "Good", "Easy"],
  reminderSet: (h) => `⏰ <b>Reminder set</b> for <b>${String(h).padStart(2, "0")}:00</b> each day, when you have cards due.`,
  reminderOff: "🔕 Reminders are off.",
  remindUsage: "Usage: /remind 20 (an hour from 0 to 23) or /remind off.",
  reminderDue: (n) => `⏰ <b>${n} card${n === 1 ? "" : "s"} due</b>\n${HR}\nA short review keeps them in memory.`,
  groupNeedsSource: "Reply to a message with the material, or write /quiz followed by a topic.",
  groupBusy: "A group quiz is already running. Send /stop to end it.",
  groupStarted: (n) => `🧠 <b>Group quiz</b>\n${HR}\n${n} questions. Everyone can answer. Points go to the leaderboard.`,
  groupNone: "No group quiz is running.",
  groupLeaderboard: (board) => `🏆 <b>Leaderboard</b>\n${HR}\n${board}`,
  deckStatus: (total, due) => `🗂️ <b>Your deck</b>\n${HR}\n${total} cards · ${due} due now`,
  cashStart: (planName, amount, number, minutes) => `💳 <b>${esc(planName)} · Vodafone Cash</b>\n${HR}\n1. Send <b>${amount} EGP</b> to <code>${esc(number)}</code>.\n2. Send me the transaction number here:\n<code>/txid 123456789</code>\n\n<i>I check it automatically. This window closes in ${minutes} minutes.</i>`,
  cashOff: "⚠️ Vodafone Cash payments are not configured yet. Try Telegram Stars from /plans.",
  cashOk: (name, until) => `🎉 <b>${esc(name)} is active</b>\n${HR}\nPaid through Vodafone Cash. Valid until <b>${esc(until)}</b>.`,
  cashPending: `⏳ <b>Not received yet</b>\n${HR}\nI can't see that payment yet. Wait a minute and send the number again.`,
  cashUsed: "⚠️ That transaction number was already used.",
  cashAmount: (got, need) => `⚠️ <b>Amount too low</b>\n${HR}\nI received <b>${got} EGP</b> but this plan needs <b>${need} EGP</b>. Contact the team if this is wrong.`,
  cashExpired: "⌛ That payment window has closed. Pick the plan again from /plans.",
  cashNoIntent: "ℹ️ Pick a plan first from /plans, then send the transaction number.",
  cashBadId: "⚠️ That doesn't look like a transaction number. Send the digits only.",
  noImages: "📸 There are no images for this file. Only PDF, Word and PowerPoint files carry images.",
  approvedN: (n) => `✅ <b>${n}</b> image${n === 1 ? "" : "s"} approved.`,
  exportDone: (n) => `📤 Sent <b>${n}</b> image${n === 1 ? "" : "s"} as albums.`,
  restoredN: (n) => `♻️ Restored <b>${n}</b> image${n === 1 ? "" : "s"} the AI had excluded.`,
  reviewedAi: (dropped, total) => `🤖 AI review done. Excluded <b>${dropped}</b> of <b>${total}</b> pending images.`,
  fileLimit: (limit) => `⛔ <b>Daily file limit reached</b>\n${HR}\nYou can upload <b>${limit}</b> files a day. The limit resets at midnight UTC.`,
  budgetDone: `⛔ <b>This file has used its 30 questions</b>\n${HR}\nEvery file can produce up to 30 quiz questions in total. Upload a new file for more.`,
  formatNote: (fmt, reason) => `⚠️ ${fmt.toUpperCase()} is not available right now (${esc(reason)}), so you received HTML.`,
  quizPick: (source, left) => `🧠 <b>How many questions?</b>\n${HR}\nSource: <b>${source === "images" ? "approved images" : "the text"}</b> · you have <b>${left}</b> left for this file.`,
  noApproved: "✅ Approve at least one image first, then the image quiz is available.",
  noQuizFromImages: "⚠️ I could not build questions from those images. Approve a clearer diagram or figure and try again.",
  pickFormat: "Output format",
  adminPaid: (name, userId, plan, amount, currency) => `💰 <b>New payment</b>\n${HR}\n${esc(name)} (<code>${userId}</code>) · <b>${esc(plan)}</b> · ${amount} ${esc(currency)}`,
  renewSoon: (until) => `⏳ <b>Your Pro ends on ${esc(until)}</b>\n${HR}\nRenew now so your files and quizzes keep working without a gap.`,
  renewExpired: `🔒 <b>Your Pro has ended</b>\n${HR}\nYou are back on the free plan. Renew any time from /plans.`,
  slowDown: "⏳ One moment, I'm still on your last request.",
  unsupportedMsg: `📎 I can read text, PDF, Word, PowerPoint and photos. Send one of those, or ask me a question in writing.`,
  streak: (n) => `🔥 <b>${n} in a row!</b> Keep going.`,
  partialRead: (note) => `📚 <b>Large file</b>\n${HR}\nI ${esc(note)}. Send the rest as a separate file if you need it all.`,
  contactRequest: `📱 <b>Verify your number</b>\n${HR}\nTo use Black Fighters, share your phone number with the button below. It is the same number Telegram has on your account.`,
  contactThanks: `✅ <b>Verified.</b> Thanks, you're all set.`,
  contactWrong: `⚠️ Please share <b>your own</b> number with the button below. Other people's contacts can't be used.`,
  adminAiDown: (lines) => `🚨 <b>AI providers failed</b>\n${HR}\n${esc(lines)}\n\n<i>Check the model names with scripts/check-ai.js and the key limits.</i>`,
  banned: `⛔ <b>This account is suspended.</b> Contact the team if you think this is a mistake.`,
  receipt: (name, until, stars, chargeId) => `🧾 <b>Receipt</b>\n${HR}\n${esc(name)} · ${stars} ⭐ · active until <b>${esc(until)}</b>\nReference: <code>${esc(chargeId)}</code>\n<i>Keep this reference if you need a refund.</i>`,
  cardsHint: "Tap a spoiler to reveal the answer.",
  cleared: `🆕 <b>Cleared.</b>\n${HR}\nSend a new file or photo any time.`,
  langSet: "🌐 Language set to <b>English</b>.",
  quota: (left, limit) => `🪙 <i>${left} of ${limit} tasks left today</i>`,
  unlimited: "👑 <i>Unlimited tasks (admin)</i>",
  stats: (s) =>
    `📈 <b>Bot stats</b>\n${HR}\nUsers today: <b>${s.activeToday}</b>\nTasks today: <b>${s.tasksToday}</b>\nFiles read today: <b>${s.filesToday}</b>\nQuizzes today: <b>${s.quizzesToday}</b>`,
  help: `🧭 <b>How to use me</b>\n${HR}\n• Send a file or photo: I read it and offer actions.\n• Paste text: same as a file.\n• Ask anything: I answer from your material when you've sent one.\n• /new clears the current material.\n• /lang ar or /lang en switches language.`,
  channelRequired: `📢 <b>Channel Subscription Required</b>\n${HR}\nTo use Black Fighters, please join our official channel first.\n\nTap the button below to join, then tap <b>Check Subscription ✅</b>.`,
  inviteInfo: ({ botUsername, userId, todayBonus, todayCount, totalCount }) =>
    `👥 <b>Invite Friends (+1 File / Day)</b>\n${HR}\nShare your invite link with your friends and study groups:\n\n🔗 <b>Your invite link:</b>\n<code>https://t.me/${botUsername}?start=ref_${userId}</code>\n\n🎁 <b>Reward:</b>\nFor every friend who joins using your link, you get <b>+1 bonus file to upload today</b>!\n\n📊 <b>Your stats:</b>\n• Today's invites: <b>${todayCount}</b>\n• Today's bonus files: <b>+${todayBonus}</b>\n• Total friends invited: <b>${totalCount}</b>`,
  providerDown: "⚠️ No AI provider is reachable right now.",
  hour: (n) => `${n} hour${n === 1 ? "" : "s"}`,
  minutes: (n) => `${n} minute${n === 1 ? "" : "s"}`,
  btn: {
    summary: "Summarize",
    detailed: "Detailed summary",
    quiz: "Quiz me",
    cards: "Flashcards",
    key: "Key points",
    explain: "Explain simply",
    ask: "Ask a question",
    topic: "Quiz on a topic",
    invite: "👥 Invite (+1 file)",
    joinChannel: "📢 Join Channel",
    checkSub: "✅ Check Subscription",
    menu: "Menu",
    newInput: "New file",
    stats: "My stats",
    langAr: "عربي",
    langEn: "English",
    next: "Next",
    results: "See result",
    again: "Another quiz",
    help: "How it works",
    back: "Back",
    buy: "Buy",
    review: "Review now",
    showAnswer: "Show answer",
    plans: "Plans",
    deck: "My deck",
    cash: "Pay with Vodafone Cash",
    shareContact: "📱 Share my number",
    format: "Format",
    cards5: "Flashcards",
  },
};

const AR = {
  welcome: (name) =>
    `✨ <b>أهلاً${name ? " " + esc(name) : ""}، أنا Black Fighters.</b>\n${HR}\nابعتلي <b>محاضرة</b> (PDF أو سلايدات أو Word أو نص) أو <b>صورة لملاحظاتك</b>. هقراها، وألخّصها، وأعملك كويز وفلاش كاردز، وأجاوب على أسئلتك منها.\n\n<i>أو اسألني أي حاجة.</i>`,
  menu: `🏠 <b>القائمة الرئيسية</b>\n${HR}\nابعت ملف أو صورة، أو اسألني أي حاجة.`,
  fileReady: ({ title, words }) =>
    `📄 <b>${esc(title)}</b>\n${HR}\n${words ? `قريت <b>${words.toLocaleString("ar-EG")}</b> كلمة. ` : ""}تحب أعمل إيه فيه؟`,
  textReady: ({ words }) => `📝 <b>النص اتستلم</b>\n${HR}\n${words} كلمة. تحب أعمل إيه فيه؟`,
  reading: "📖 بقرا الملف…",
  extracting: "🔍 بستخرج النص…",
  thinking: "🧠 بفكّر…",
  writing: "✍️ بكتب…",
  askPrompt: `💬 <b>اسأل براحتك</b>\n${HR}\nاكتب سؤالك. هجاوب من الملف اللي بعته، ولو مفيش ملف هجاوب من المعرفة العامة.`,
  topicPrompt: `🎯 <b>كويز على موضوع</b>\n${HR}\nاكتب الموضوع، مثلاً <i>العرض والطلب</i>.`,
  noInput: `📎 <b>مفيش حاجة أشتغل عليها</b>\n${HR}\nابعت ملف أو صورة، أو الصق نص الأول.`,
  tooBig: (mb) => `⚠️ الملف ده أكبر من <b>${mb} ميجا</b>. البوتات بتقدر تنزل لحد ${mb} ميجا. جرّب ملف أصغر.`,
  unsupported: "⚠️ نوع الملف ده مش مدعوم لسه. ابعت PDF أو Word (.docx) أو PowerPoint (.pptx) أو نص أو صورة.",
  unreadable: "⚠️ معرفتش أقرا أي نص هنا. جرّب PDF فيه نص قابل للتحديد، أو صورة أوضح.",
  failed: "⚠️ الذكاء الاصطناعي مشغول دلوقتي. جرّب تاني بعد شوية.",
  quotaReached: (limit, resetIn) =>
    `⛔ <b>وصلت للحد اليومي</b>\n${HR}\nخلّصت كل المهام الـ <b>${limit}</b> لليوم ده. ارجع بعد <b>${resetIn}</b>. الأسئلة والشات مجانيين.`,
  busy: "⏳ لسه بشتغل على طلبك اللي قبله. استنى لحظة.",
  quizIntro: (n) => `🧠 <b>وقت الكويز</b>\n${HR}\n<b>${n}</b> سؤال. دوس على الإجابة. بالتوفيق.`,
  quizQuestion: ({ index, total, q }) => `🧠 <b>سؤال ${index} من ${total}</b>\n${HR}\n${esc(q)}`,
  right: (explanation) => `✅ <b>صح.</b>${explanation ? `\n<i>${esc(explanation)}</i>` : ""}`,
  wrong: (correct, explanation) =>
    `❌ <b>لأ، مش دقيقة.</b>\nالإجابة الصح: <b>${esc(correct)}</b>.${explanation ? `\n<i>${esc(explanation)}</i>` : ""}`,
  quizDone: (score, total) => {
    const pct = total ? Math.round((score / total) * 100) : 0;
    const verdict = pct === 100 ? "ممتاز بالكامل." : pct >= 70 ? "شغل قوي." : pct >= 40 ? "بداية كويسة. راجع الأسئلة اللي غلطت فيها." : "كمّل. راجع بسرعة وجرّب تاني.";
    return `🏆 <b>النتيجة: ${score} من ${total}</b> (${pct}%)\n${HR}\n${verdict}`;
  },
  styles: `🎨 <b>اختار الستايل</b>\n${HR}\nكل ستايل بيذاكر نفس المادة بطريقة مختلفة. النتيجة ملف HTML نضيف تفتحه في أي متصفح وتطبعه PDF.`,
  styleLanguage: "لغة الملف",
  figureAdded: (caption, n) => `🖼️ <b>اتضافت صورة</b>${caption ? `: ${esc(caption)}` : ""}\n<i>${n} صورة جاهزة للملف الجاي.</i>`,
  figureFull: "⚠️ عندك 6 صور لنفس المادة. ابدأ ملف جديد عشان تضيف أكتر.",
  figureTooBig: "⚠️ الصورة دي أكبر من 900 كيلو. ابعت صورة أصغر.",
  docReady: "📎 الملف متبعت. افتحه في أي متصفح، أو اطبعه PDF.",
  docCaption: (name) => `📎 ${name}\nافتحه في أي متصفح. اطبع، واختار Save as PDF.`,
  plansTitle: `⭐ <b>الباقات</b>\n${HR}\nادفع بـ Telegram Stars. من غير كارت، ومن غير مزود دفع خارجي.`,
  paid: (name, until) => `🎉 <b>${esc(name)} اتفعّل</b>\n${HR}\nساري لحد <b>${esc(until)}</b>. استمتع بالمساحة الإضافية.`,
  paidFailed: "⚠️ الدفعة دي متقدرتش تترط على باقة. لو اتخصم منك، ابعت الإيصال للفريق.",
  deckAdded: (n) => `🗂️ اتضاف ${n} كارت للمراجعة. استخدم /review عشان تراجعهم.`,
  reviewNone: (total) => total ? `✅ <b>مفيش حاجة مستحقة دلوقتي.</b>\n${HR}\nعندك ${total} كارت. ارجع بعدين.` : `🗂️ <b>مجموعة المراجعة فاضية.</b>\n${HR}\nاعمل فلاش كاردز من أي مادة وهتتحفظ هنا.`,
  reviewQuestion: (q, left) => `🔁 <b>مراجعة</b> · ${left} مستحق\n${HR}\n${esc(q)}`,
  reviewAnswer: (q, a) => `🔁 <b>مراجعة</b>\n${HR}\n<b>${esc(q)}</b>\n\n${esc(a)}\n\n<i>قد إيه كنت فاكره؟</i>`,
  reviewNext: (days) => days < 1 ? `✅ تمام. هتشوفه تاني بعد حوالي 10 دقايق.` : `✅ تمام. المراجعة الجاية بعد ${days} يوم.`,
  grades: ["نسيته", "صعب", "جيد", "سهل"],
  reminderSet: (h) => `⏰ <b>التذكير اتضبط</b> الساعة <b>${String(h).padStart(2, "0")}:00</b> كل يوم لما يكون عندك كروت مستحقة.`,
  reminderOff: "🔕 التذكيرات اتقفلت.",
  remindUsage: "الاستخدام: /remind 20 (ساعة من 0 لـ 23) أو /remind off.",
  reminderDue: (n) => `⏰ <b>${n} كارت مستحق</b>\n${HR}\nمراجعة قصيرة بتخلّيهم فاكرين.`,
  groupNeedsSource: "رد على رسالة فيها المادة، أو اكتب /quiz والموضوع.",
  groupBusy: "فيه كويز جروب شغال. ابعت /stop عشان تقفله.",
  groupStarted: (n) => `🧠 <b>كويز جروب</b>\n${HR}\n${n} سؤال. الكل يقدر يجاوب. النقط بتروح للوحة المتصدرين.`,
  groupNone: "مفيش كويز جروب شغال.",
  groupLeaderboard: (board) => `🏆 <b>لوحة المتصدرين</b>\n${HR}\n${board}`,
  deckStatus: (total, due) => `🗂️ <b>مجموعتك</b>\n${HR}\n${total} كارت · ${due} مستحق دلوقتي`,
  cashStart: (planName, amount, number, minutes) => `💳 <b>${esc(planName)} · فودافون كاش</b>\n${HR}\n1. ابعت <b>${amount} جنيه</b> على <code>${esc(number)}</code>.\n2. ابعتلي رقم العملية هنا:\n<code>/txid 123456789</code>\n\n<i>بتحقق منها تلقائياً. النافذة دي بتقفل بعد ${minutes} دقيقة.</i>`,
  cashOff: "⚠️ الدفع بفودافون كاش مش متظبط لسه. جرّب Telegram Stars من /plans.",
  cashOk: (name, until) => `🎉 <b>${esc(name)} اتفعّل</b>\n${HR}\nاتدفع بفودافون كاش. ساري لحد <b>${esc(until)}</b>.`,
  cashPending: `⏳ <b>لسه متوصلش</b>\n${HR}\nمش لاقي الدفعة دي لسه. استنى دقيقة وابعت الرقم تاني.`,
  cashUsed: "⚠️ رقم العملية ده اتستخدم قبل كده.",
  cashAmount: (got, need) => `⚠️ <b>المبلغ أقل من المطلوب</b>\n${HR}\nوصلني <b>${got} جنيه</b> والباقة دي محتاجة <b>${need} جنيه</b>. كلم الفريق لو ده غلط.`,
  cashExpired: "⌛ النافذة دي اتقفلت. اختار الباقة تاني من /plans.",
  cashNoIntent: "ℹ️ اختار باقة الأول من /plans، وبعدين ابعت رقم العملية.",
  cashBadId: "⚠️ ده مش شكل رقم عملية. ابعت الأرقام بس.",
  noImages: "📸 مفيش صور للملف ده. ملفات PDF وWord وPowerPoint بس هي اللي فيها صور.",
  approvedN: (n) => `✅ اتعتمد <b>${n}</b> صورة.`,
  exportDone: (n) => `📤 اتبعت <b>${n}</b> صورة كألبوم.`,
  restoredN: (n) => `♻️ رجّعت <b>${n}</b> صورة الـ AI كان مستبعدها.`,
  reviewedAi: (dropped, total) => `🤖 خلّصت مراجعة الـ AI. استبعدت <b>${dropped}</b> من <b>${total}</b> صورة مستنية.`,
  fileLimit: (limit) => `⛔ <b>وصلت للحد اليومي للملفات</b>\n${HR}\nتقدر ترفع <b>${limit}</b> ملفات في اليوم. الحد بيتجدد نص الليل بتوقيت UTC.`,
  budgetDone: `⛔ <b>الملف ده خلّص الـ 30 سؤال بتوعه</b>\n${HR}\nكل ملف يطلع لحد 30 سؤال كويز في الإجمالي. ارفع ملف جديد عشان تزود.`,
  formatNote: (fmt, reason) => `⚠️ ${fmt.toUpperCase()} مش متاح دلوقتي (${esc(reason)})، فاتبعتلك HTML.`,
  quizPick: (source, left) => `🧠 <b>عدد الأسئلة؟</b>\n${HR}\nالمصدر: <b>${source === "images" ? "الصور المعتمدة" : "النص"}</b> · فاضل <b>${left}</b> سؤال للملف ده.`,
  noApproved: "✅ اعتمد صورة واحدة على الأقل الأول، وبعدين الكويز من الصور يبقى متاح.",
  noQuizFromImages: "⚠️ معرفتش أطلع أسئلة من الصور دي. اعتمد رسمة أو شكل أوضح وجرّب تاني.",
  pickFormat: "صيغة الملف",
  adminPaid: (name, userId, plan, amount, currency) => `💰 <b>دفعة جديدة</b>\n${HR}\n${esc(name)} (<code>${userId}</code>) · <b>${esc(plan)}</b> · ${amount} ${esc(currency)}`,
  renewSoon: (until) => `⏳ <b>برو بتاعك بيخلص يوم ${esc(until)}</b>\n${HR}\nجدّده دلوقتي عشان ملفاتك وكويزاتك تفضل شغالة من غير فراغ.`,
  renewExpired: `🔒 <b>برو بتاعك خلص</b>\n${HR}\nرجعت للباقة المجانية. جدّد في أي وقت من /plans.`,
  slowDown: "⏳ لحظة، لسه بشتغل على طلبك اللي قبله.",
  unsupportedMsg: `📎 أقدر أقرا نص وPDF وWord وPowerPoint وصور. ابعت واحد منهم، أو اسألني سؤال مكتوب.`,
  streak: (n) => `🔥 <b>${n} صح على التوالي!</b> كمّل كده.`,
  partialRead: (note) => `📚 <b>ملف كبير</b>\n${HR}\nقريت ${esc(note)}. ابعت باقي الملف كملف منفصل لو محتاجه كله.`,
  contactRequest: `📱 <b>أكّد رقمك</b>\n${HR}\nعشان تستخدم Black Fighters، شارك رقم تليفونك بالزرار اللي تحت. ده نفس الرقم اللي تيليجرام مسجله على حسابك.`,
  contactThanks: `✅ <b>اتأكد رقمك.</b> شكراً، كل حاجة جاهزة.`,
  contactWrong: `⚠️ شارك <b>رقمك أنت</b> بالزرار اللي تحت. مينفعش جهات اتصال حد تاني.`,
  adminAiDown: (lines) => `🚨 <b>مزودو الذكاء الاصطناعي فشلوا</b>\n${HR}\n${esc(lines)}\n\n<i>راجع أسماء الموديلات بـ scripts/check-ai.js وحدود المفاتيح.</i>`,
  banned: `⛔ <b>الحساب ده موقوف.</b> كلم الفريق لو فيه غلط.`,
  receipt: (name, until, stars, chargeId) => `🧾 <b>إيصال</b>\n${HR}\n${esc(name)} · ${stars} ⭐ · ساري لحد <b>${esc(until)}</b>\nالمرجع: <code>${esc(chargeId)}</code>\n<i>احتفظ بالمرجع ده لو محتاج استرداد.</i>`,
  cardsHint: "دوس على الكلام المخفي عشان تشوف الإجابة.",
  cleared: `🆕 <b>اتمسح.</b>\n${HR}\nابعت ملف أو صورة جديدة في أي وقت.`,
  langSet: "🌐 اللغة بقت <b>العربي</b>.",
  quota: (left, limit) => `🪙 <i>باقي ${left} من ${limit} مهمة النهارده</i>`,
  unlimited: "👑 <i>مهام بدون حد (أدمن)</i>",
  stats: (s) =>
    `📈 <b>إحصائيات البوت</b>\n${HR}\nمستخدمين النهارده: <b>${s.activeToday}</b>\nمهام النهارده: <b>${s.tasksToday}</b>\nملفات اتقرت: <b>${s.filesToday}</b>\nكويزات: <b>${s.quizzesToday}</b>`,
  help: `🧭 <b>إزاي تستخدمني</b>\n${HR}\n• ابعت ملف أو صورة: بقرأه وبعرض عليك الأفعال.\n• الصق نص: زي الملف بالظبط.\n• اسألني أي حاجة: بجاوب من مادتك لو بعتها.\n• /new بيمسح المادة الحالية.\n• /lang ar أو /lang en بيغيّر اللغة.`,
  channelRequired: `📢 <b>تنبيه: يجب الاشتراك في القناة أولاً!</b>\n${HR}\nلاستخدام البوت والاستفادة من جميع المميزات (تلخيص المحاضرات، الكويزات، الفلاش كاردز)، يجب الانضمام لقناة البوت الرسمية أولاً.\n\nاضغط على الزر بالأسفل للاشتراك، ثم اضغط على <b>تحقق من الاشتراك ✅</b>.`,
  inviteInfo: ({ botUsername, userId, todayBonus, todayCount, totalCount }) =>
    `👥 <b>نظام دعوة الأصدقاء (+1 ملف لليوم)</b>\n${HR}\nشارك رابط الدعوة الخاص بك مع زملائك في الكلية أو الجروبات:\n\n🔗 <b>رابط الدعوة الخاص بك:</b>\n<code>https://t.me/${botUsername}?start=ref_${userId}</code>\n\n🎁 <b>المكافأة:</b>\nلكل صديق يسجل من خلال رابطك، ستحصل على <b>+1 ملف إضافي لرفعه اليوم</b>!\n\n📊 <b>إحصائياتك:</b>\n• دعوات اليوم: <b>${todayCount}</b> صديق\n• الملفات الإضافية اليوم: <b>+${todayBonus}</b> ملف\n• إجمالي الأصدقاء المدعوين: <b>${totalCount}</b> صديق`,
  providerDown: "⚠️ مفيش مزوّد ذكاء اصطناعي شغال دلوقتي.",
  hour: (n) => `${n} ساعة`,
  minutes: (n) => `${n} دقيقة`,
  btn: {
    summary: "لخّص",
    detailed: "ملخص تفصيلي",
    quiz: "اعملي كويز",
    cards: "فلاش كاردز",
    key: "أهم النقاط",
    explain: "اشرحه ببساطة",
    ask: "اسأل سؤال",
    topic: "كويز على موضوع",
    invite: "👥 دعوة أصدقاء (+1 ملف)",
    joinChannel: "📢 انضم للقناة الآن",
    checkSub: "✅ تحقق من الاشتراك",
    menu: "القائمة",
    newInput: "ملف جديد",
    stats: "إحصائياتي",
    langAr: "عربي",
    langEn: "English",
    next: "التالي",
    results: "شوف النتيجة",
    again: "كويز تاني",
    help: "إزاي بشتغل",
    back: "رجوع",
    buy: "اشترك",
    review: "راجع دلوقتي",
    showAnswer: "اعرض الإجابة",
    plans: "الباقات",
    deck: "مجموعتي",
    cash: "ادفع بفودافون كاش",
    shareContact: "📱 شارك رقمي",
    format: "الصيغة",
    cards5: "فلاش كاردز",
  },
};

export function copy(lang) {
  return lang === "ar" ? AR : EN;
}
